name: Hello World
on: [push, workflow_dispatch]
jobs:
  Hello-World-Job:
    runs-on:
      - GHRunner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
      - name: S3 ls
        shell: bash
        run: |
          echo "list bucket"
          aws s3 ls output.json
          cat output.json    
